version: '3.8'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASS}
      MYSQL_DATABASE: database
      MYSQL_USER: ${DATABASE_LOGIN}
      MYSQL_PASSWORD: ${DATABASE_PASS}
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      retries: 50
      start_period: 0s
      timeout: 2s
  backend:
    build:
      context: ./backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - '8080:8080'
      - '5005:5005'
    volumes:
      - ./backend:/backend
    working_dir: /backend
    env_file:
      - .env
    environment:
      - DATABASE_URL=jdbc:mysql://mysql:3306/database