kotki-pieski:
  jwt-secret: ${JWT_SECRET}
  expiration-time: ${TOKEN_EXPIRATION_TIME}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /api/v1/docs/index.html
  api-docs:
    path: /api/v1/docs/schema

spring:
  application:
    name: Backend
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_LOGIN}
    password: ${DATABASE_PASS}
  security:
    user:
      name: abc
      password: def
  devtools:
    livereload:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: TRACE
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE